### ISSUE TITLE
didn't manage to start up the example?

### ISSUE THREAD

**Issue by nohkumado** [dukefirehawk/boilerplates#8]
Hello!

i cloned the postgres sample project and tried to follow the readme, but the example doesn't start up...
first of all the config/default.yaml has no default postgres section but one for mongodb.... so i tried to adapt:

```
    jwt_secret: INSECURE_DEFAULT_SECRET
   host: 127.0.0.1
   #mongo_db: mongodb://localhost:27017/angel
   port: 3000
   postgres:
      host: 192.168.67.3
      port: 5435
      database_name: angeldb
      username: appuser
      password:myawesomepasswd
      useSSL: false
      time_zone: UTC
```
concerning the db, i connect to it through psql just fine!

the migrate.dart was not found, so i went straight to 
```
   dart --observe bin/dev.dart
```

but that gives me :
```
   The Dart VM service is listening on http://127.0.0.1:8181/NFSA990E-H8=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/NFSA990E-H8=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2FNFSA990E-H8%3D%2Fws
vm-service: isolate (1779380118800147) 'main' has no debugger attached and is paused due to exception.  Connect to the Dart VM service at http://127.0.0.1:8181/NFSA990E-H8=/ to debug.
```

no service on port 3000 and the link for the debugger i don't know how to read, so what did i do wrong?

so.... installing the angel_cli and instead of cloning the repo install it through angel3 init hello did solve the first part...

now i have migration but:

```
   dart bin/migrate.dart up
Unhandled exception:
TimeoutException after 0:00:30.000000: Future not completed
```
 
dose tis mean it doesn't reach the db? i don't see any relations created over there?

argh... ok answering myself, i leave this maybe the docu could be updated in that respect, in the example you use a # in the password, looks that was a mighty bad idea ;) choosing a password without dangerous (should need the list somewhere) chars solves the problem....

migrations successful, tables created....
server fired up, servinge a page with Angel in it...
